Add C/C++ test using cppcheck
tasostefas/opendr_internal pull request #113
Opened 2021-07-21 16:13 UTC by stefaniapedrazzi

Run cppcheck on C/C++ files and update the version if clang-format.

2021-07-22 09:11 UTC, stefaniapedrazzi commented
Tests passes after disabling the `object_tracking_2d` tests that are currently failing on master.

2021-07-26 11:58 UTC, stefaniapedrazzi commented
I would temporary disable the `object_tracking_2d` as it is breaking the tests on all the PRs.

2021-08-02 08:11 UTC, vniclas commented on tests/test_cppcheck.py
> +                            continue
This `continue` does not have any effect.

2021-08-02 08:47 UTC, vniclas approved these changes

2021-08-02 08:49 UTC, vniclas requested changes
There are errors reported by `cppcheck` but the tests are not failing.

2021-08-02 09:21 UTC, stefaniapedrazzi commented
> There are errors reported by `cppcheck` but the tests are not failing.

For the moment we don't have any C/C++ files to check and this is what `cppcheck` is reporting .
I checked and errors in C/C++ makes the test failing correctly.
Moreover as soon as at least one C/C++ file is found the current errors disappear.
So it is correct that the current errors, even if printed in the log, don't make the test fail.

2021-08-02 09:24 UTC, vniclas commented
Thanks for following up on this!

2021-08-02 09:24 UTC, vniclas approved these changes

2021-08-17 07:12 UTC, vniclas approved these changes

2021-08-20 06:15 UTC, passalis approved these changes
Thank you! Seems fine.

2021-08-23 06:59 UTC, merged