Detr demos and tutorial
tasostefas/opendr_internal pull request #146
Opened 2021-10-29 11:43 UTC by jelledouwe

Dear reviewers,

Here are some minor changes for the DetrLearner. One of the argument names is changed to make it more informative and a utility method for drawing results is add. Furthermore, demos and an inference tutorial are created and the documentation is updated accordingly.

2021-11-01 07:30 UTC, ad-daniel requested changes
Very good, thank you!

2021-11-01 07:30 UTC, ad-daniel commented on docs/reference/detr.md
>  Parameters:
```suggestion

Parameters:
```

2021-11-01 07:30 UTC, ad-daniel commented on docs/reference/detr.md
>  Parameters:
```suggestion

Parameters:
```

2021-11-01 07:30 UTC, ad-daniel commented on projects/perception/object_detection_2d/detr/README.md
> +OpenDR.
```suggestion
This folder contains minimal code usage examples that showcase the basic functionality of the DetrLearner provided by OpenDR. 
```

2021-11-01 07:30 UTC, ad-daniel commented on projects/perception/object_detection_2d/detr/README.md
> +OpenDR.
one sentence per line

2021-11-01 07:30 UTC, ad-daniel commented on src/opendr/perception/object_detection_2d/detr/README.md
> +is used in the [drawing utility function](algorithm/util/draw.py).
```suggestion
Also, code from [here](https://stackoverflow.com/questions/60674501/how-to-make-black-background-in-cv2-puttext-with-python-opencv) is used in the [drawing utility function](algorithm/util/draw.py).
```

2021-11-01 09:34 UTC, ad-daniel approved these changes
Thank you!

2021-11-02 05:32 UTC, passalis approved these changes
Nice work! Thank you!

2021-11-02 08:34 UTC, merged