ROS node for hand gesture recognition
tasostefas/opendr_internal pull request #153
Opened 2021-11-28 17:00 UTC by katerynaCh

This PR implements a ROS node for rgbd_hand_gesture_learner.

2021-11-28 19:36 UTC, passalis requested changes
Thank you! Overall seems fine. Please move the generic translation functionality into the bridge package, as well as please add the name of the node into the list of available nodes in [](https://github.com/tasostefas/opendr_internal/blob/master/projects/opendr_ws/README.md)

2021-11-28 19:36 UTC, passalis commented on projects/opendr_ws/src/perception/scripts/rgbd_hand_gesture_recognition.py
> +def from_category(prediction, source_data=None):
Please move this generic functionality to [projects/opendr_ws/src/ros_bridge/src/opendr_bridge/bridge.py](https://github.com/tasostefas/opendr_internal/blob/master/projects/opendr_ws/src/ros_bridge/src/opendr_bridge/bridge.py).

2021-11-28 19:38 UTC, passalis commented on projects/opendr_ws/src/perception/scripts/rgbd_hand_gesture_recognition.py
> +def from_category(prediction, source_data=None):
Also, after moving the corresponding function to bridge.py please update the corresponding documentation (https://github.com/tasostefas/opendr_internal/blob/master/docs/reference/rosbridge.md).

2021-11-29 05:45 UTC, passalis submitted a review, later dismissed
Thank you!

2021-11-29 07:11 UTC, ad-daniel submitted a review, later dismissed
Thank you!

2021-11-29 12:42 UTC, ad-daniel commented
Looks like there are a few formatting fixes that need to be done before being able to merge

2021-11-29 18:31 UTC, passalis approved these changes

2021-11-29 18:56 UTC, merged