Object Detection 3D Bug fixes
tasostefas/opendr_internal pull request #55
Opened 2021-04-21 14:59 UTC by iliiliiliili

Fixed the bug with wrong score for iterator-based evaluation and fixed the usage of absolute paths in save/load functions.

2021-07-22 09:13 UTC, stefaniapedrazzi commented
I convert this PR to draft.
Please change the status when it is ready for review.

2021-10-01 07:11 UTC, ad-daniel requested changes
Looks good to me

2021-10-04 06:25 UTC, ad-daniel approved these changes
Thank you.

2021-10-04 07:20 UTC, passalis approved these changes
Thank you for this bugfix! I had one minor comment that puzzled me (even though it does not alter the functionality of the code).

2021-10-04 08:20 UTC, iliiliiliili commented on src/opendr/engine/target.py
> +        index = list(range(num_objects)) + [-1] * (num_ground_truths - num_objects)
The Kitti format of a single box is made to be identical to the one with a list of boxes, and, I think, it's better to keep it like that for easier possible future updates.

2021-10-04 08:20 UTC, merged