Speech command recognition - MatchboxNet
tasostefas/opendr_internal pull request #58
Opened 2021-04-26 13:11 UTC by jovaroo

Adds an implementation of MatchboxNet, which can be used for keyword spotting or other limited-vocabulary speech recognition tasks.

2021-06-28 05:28 UTC, passalis commented
@jovaroo testing is now available again. So, when you are ready, you can use the "test sources" label to run the style checks and "test tools" to run the tool tests.

2021-06-29 04:30 UTC, jovaroo commented
@passalis The tests have now successfully run and the PR is ready for final review!

2021-06-29 05:07 UTC, passalis submitted a review, later dismissed
Thanks!

2021-06-29 18:02 UTC, stefaniapedrazzi requested changes
Thank you!
Everything is fine for me as well.
It would just be good to log the test name at the very beginning.

2021-06-29 18:02 UTC, stefaniapedrazzi commented on tests/sources/tools/perception/speech_recognition/matchboxnet/test_matchboxnet.py
> +    def setUpClass(cls):
Could you please add a log message specifying which test is running?
Something like this:
```suggestion
    def setUpClass(cls):
        print("\n\n**********************************\nTEST Speech command recognition MatchboxNetLearner\n"
              "**********************************")
```

2021-06-30 08:41 UTC, jovaroo commented
@stefaniapedrazzi Applied the suggested change!

2021-06-30 09:30 UTC, stefaniapedrazzi approved these changes
Thank you!

2021-06-30 09:42 UTC, passalis approved these changes

2021-07-01 02:13 UTC, merged